### ISSUE TITLE
TypeError: Cannot read property 'books' of undefined

### ISSUE THREAD

**Issue by sillygwailo** [sillygwailo/goodreads-random#3]
The app crashes periodically, with this error. More logging is needed to see what triggers this, and/or what action a user takes before it happens:

```
TypeError: Cannot read property 'books' of undefined
    at /app/app.js:92:41
    at /app/node_modules/goodreads/lib/goodreads/goodreads.js:165:18
    at Parser.<anonymous> (/app/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:315:20)
    at SAXParser.onclosetag (/app/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/app/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/app/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/app/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/app/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/parser.js:323:31)
Emitted 'error' event on Parser instance at:
    at Parser.exports.Parser.Parser.parseString (/app/node_modules/xml2js/lib/parser.js:327:16)
    at Parser.parseString (/app/node_modules/xml2js/lib/parser.js:5:59)
    at Request._callback (/app/node_modules/goodreads/lib/goodreads/goodreads.js:164:23)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/app/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
```

**Comment by sillygwailo** [comment]
This was "fixed" in commit dfa7891db7bf32c2d7e22b48e24a315c9ffb0e99 by adding a check to see if it's undefined. If there's a failure, nothing will be returned, but it will log information.
